Repository martin-g/http2-server-perf-tests, pull requests merged in 2020-10, with the labels that each got.

#2 http2 server perf for asp.net core 3.1
  .gitignore
  netcore/Program.cs
  netcore/README.md
  netcore/netcore-http2.csproj
Labels: size/M

#3 changed to use a pfx file instead of crt/key combination
  .gitignore
  netcore/Program.cs
  netcore/README.md
  netcore/generate-cert.ps1
  netcore/generate-cert.sh
Labels: size/M

#4 reduced logging level to Error
  netcore/Program.cs
  netcore/appsettings.json
Labels: size/S

#5 Run in release mode
  netcore/README.md
Labels: size/XS
